### ISSUE TITLE
Several PID schemes are currently missing, and DOI fails

### ISSUE THREAD

**Issue by wouteraddink** [pangaea-data-publisher/fuji#189]
Several PID schemes are currently missing, on my wish list to add would be: ORCID, ROR, GRID, CETAF Identifiers. Also if I enter a DOI, it reports not resolvable while it actually is (tested with: https://doi.org/10.15553/c2016v711a3)

**Comment by huberrob** [comment]
Dera Wouter,

F-UJI recognizes identifiers which are commonly used for **research data**, therefore ORCID, ROR and GRID are not supported since they are used for other purposes/entities.

CETAF are problematic since they are loosely defined and cannot be distinguished from URLs. Further, they most likely do not comply with the EOSC pid policy. See also https://github.com/pangaea-data-publisher/fuji/issues/158

The DOI you sent is very interesting, the resolver seems to send a 308 status code which is not listed in [RFC 2616](https://datatracker.ietf.org/doc/html/rfc2616.html) this is causing the request library to raise an error. 
Meanwhile, [RFC 7538](https://datatracker.ietf.org/doc/html/rfc7538) has been proposed which defines 308 and there seems to be patch for urllib which is not yet part of the distribution ... I will see if this solves the problem.

Robert

**Comment by huberrob** [comment]
This patch: https://github.com/python/cpython/pull/19588/commits works and solves the 308 problem..

**Comment by wouteraddink** [comment]
@huberrob that is great! Regarding what the tool is for, it depends how you define a Research Data Object. If you see that as an object containing research data then it is fine not to support ROR or ORCID, but if you see it as a data object used in research then these should be included. The tool seems to assume datasets, while in modern science the boundaries between datasets and individual data objects will probably fade: it will no longer be needed to exchange whole datasets but rather in a data fabric of fair digital objects the individual objects will be exchanged which may be as small as nanopublications.
