### ISSUE TITLE
Document expectations towards a metadata endpoint. Here: RDF/SPARQL

### ISSUE THREAD

**Issue by sneumann** [pangaea-data-publisher/fuji#263]
Hi, 
https://www.f-uji.net/?action=test is able to query endpoints providing OAI-PMH, SPARQL, CSW. 
There should be some docs somewhere what is expected from those endpoints, or which have been successfully tested. For SPARQL, it should mention the actual endpoints / triplestores (I'd expect most/all would work ?).

But more importantly it should specify what RDF triples FUJI is expecting there. Seems the data and attributes expected are in such queries:
https://github.com/pangaea-data-publisher/fuji/blob/3e2f6d20e5620fae813de4d450403179f78dc218/fuji_server/helper/metadata_mapper.py#L212
or specific queries:
https://github.com/pangaea-data-publisher/fuji/blob/3e2f6d20e5620fae813de4d450403179f78dc218/fuji_server/helper/metadata_mapper.py#L142
executed in this class:
https://github.com/pangaea-data-publisher/fuji/blob/49c99ef4bdf1a0578dc61bc9e7eb555693887a05/fuji_server/helper/metadata_provider_sparql.py#L30

and available to FUJI through this class:
https://github.com/pangaea-data-publisher/fuji/blob/3fbd229b65e8c85d94673c553ea20edef59e6cd4/fuji_server/helper/metadata_collector_rdf.py#L44

So in the absence of the requested documentation, this issue can serve in its place :-) 

Yours, Steffen

**Comment by huberrob** [comment]
Dear Steffen,

I know this is confusing, but these endpoints are not used to retrieve metadata itself but to check which metadata formats and vocabularies are supported by a given data provider. Therefore they are only used in e.g. FsF-I1-02M, FsF-R1.3-01M and FsF-I1-01M.
The reason is, that e.g. it is impossible to retrieve metadata for a given DOI using OAI-PMH and at least the few SPARQL endpoints I have seen and tried for testing astonishingly didn't contain PIDs. Maybe this can be improved in the future.

Robert
