### ISSUE TITLE
" WARNING: Landing page seems to be JavaScript generated, could not detect enough content ". for Gesis PIDs

### ISSUE THREAD

**Issue by zhangyggesis** [pangaea-data-publisher/fuji#336]
We, Gesis, uses compressed Javascripts on landing pages.  When we use F-uji tool to test our PIDs such as 10.4232/1.1305, the F-uji tool metadata harvester issues the following warning:
----
" WARNING: Landing page seems to be JavaScript generated, could not detect enough content ".
----

Therefore we get NO score for the metric below.

---
FsF-I1-01M-1 | Parsable, structured metadata (JSON-LD, RDFa) is embedded in the landing page XHTML/HTML code 
--

We believe this is because F-uji tool cannot deal with compressed Javascripts on our landing page.   We are wondering if this can be changed so that the F-uji tool can deal with the compressed javascript to detect the content.

Thanks, yudong from Gesis.

**Comment by huberrob** [comment]
F-UJI does not execute any JS code so JS compression should not be the reason. Can you please post the DOI/URL of an example dataset?

**Comment by zhangyggesis** [comment]
The doi is 10.4232/1.1305

**Comment by huberrob** [comment]
OK, thanks. The problem here is that the page is completely JS generated including e.g. your schema.org metadata description in the HEAD section (see below) this makes it quite machine unfriendly which would have to execute the JS to see this. 
If you want to provide this in a way F-UJI can discover the schema.org metadata just avoid JS here.

`<script id="dynamicJSONLD" type="application/ld+json">{"@context":"http://schema.org/","provider":{"@type":"Organization","name":"GESIS search","url":"https://search.gesis.org","description":"Find information about social science research data and open access publications"},"@type":"Dataset","@id":"https://doi.org/10.4232/1.1305","version":["1.0.0"],"name":"Wachsende Disharmonien zwischen staatlichem Leistungsangebot und gesellschaftlicher Nachfrage","creator":[{"@type":"Organization","name":"Mackscheidt, Klaus"},{"@type":"Organization","name":"Oepen, Georg von"}],"url":"https://search.gesis.org/research_data/ZA1305","datePublished":["2010-04-13"],"publisher":{"@type":"Organization","name":"GESIS Data Archive","sameAs":"https://www.gesis.org"},"inLanguage":[{"@type":"Language","name":"English"},{"@type":"Language","name":"German"}],"identifier":{"@type":"PropertyValue","propertyID":"ZA-No.","value":"ZA1305"},"keywords":["Gemeinde, Wohnumgebung, Stadtleben und Landleben","Soziales Verhalten und soziale Einstellungen","Sozialpolitik","Sozialsysteme und Strukturen der Sozialfürsorge","Wirtschaftspolitik, öffentliche Ausgaben und Einnahmen","Community, urban and rural life","Social behaviour and attitudes","Social welfare policy","Social welfare systems/structures","Economic policy,  public expenditure and revenue"],"description":"Beurteilung des staatlichen Leistungsangebots.\n\nThemen: Persönlicher Nutzen aus gezahlten Steuern; wichtigste Aufgaben\nzukünftiger Staatstätigkeit; Beurteilung der Sinnhaftigkeit von\nStaatsausgaben in ausgewählten Bereichen; wichtigste Bereiche für eine\nReprivatisierung staatlicher Leistungen; Bewertung der Höhe der\nStaatsausgaben; von Steuererhöhungen besonders betroffene Gruppen;\nSteuergerechtigkeit; wichtigste Bereiche öffentlicher Verschwendung;\nvorhandene sowie vermißte Dienststellen und Behörden im eigenen\nWohnbereich; für notwendig und als förderungswürdig erachtete\nöffentliche Einrichtungen im eigenen Wohngebiet; Einschätzung der\nAttraktivität des Wohngebiets; Charakteristika des Wohnumfelds;\nZufriedenheit mit der Lebens- und Wohnsituation im Stadtteil;\ntatsächliche und gewünschte Nachbarschaftskontakte; Umzugsabsichten;\nOrtsansässigkeit; Freizeitbeschäftigungen; Zufriedenheit mit dem\nArbeitsplatzangebot in der Stadt; Präferenz für staatliche oder\nprivatwirtschaftliche Kontrolle über das Gesundheitswesen,\nGroßunternehmen, sozialen Einrichtungen und Schulen; bevorzugte\nFinanzierungsform (Steuererhöhung, Selbsthilfe oder Gebühren)\nausgewählter öffentlicher Einrichtungen; Bereiche für finanzielle\nKürzungen; eigene Inanspruchnahme staatlicher Leistungen; Wichtigkeit\nausgewählter staatlicher Leistungen (Rangordnung); Schwellenangst bei\nBehördengängen (Skala); präferierte Methoden politischer Einflußnahme;\nrelatives Verhältnis empfangener Staatsleistungen und eigener\nSteuerzahlungen; gesellschaftliche Gruppen, für die in der BRD zukünftig\nmehr getan werden sollte; Charakterisierung von Behörden und Ämtern\n(Semantisches Differential); perzipierte Ursachen für Einkommens- und\nVermögensunterschiede; tatsächliche und ideale Vorstellungen über die\nLebenssituation; Präferenz für mehr Staat- oder mehr Privatwirtschaft\nzur Erreichung finanzieller und äußerer Sicherheit sowie für die\nGewährleistung persönlichen Lebensraums, Schutz vor Verbrechen und\nSicherheit der Arbeitsplätze; Wichtigkeit ausgewählter\nStaatstätigkeiten; allgemeine Beurteilung des Umfangs staatlicher\nTätigkeiten; Einstellung zur steuerfinanzierten staatlichen\nAufgabenerhöhung; Leistungsorientierung; gewünschte Entwicklung der\nStaatsausgaben in ausgewählten Bereichen; wichtigste Informationsquellen\nüber Politik; Arbeitszufriedenheit (Skala); soziale Herkunft; Alter der\nKinder; Ausbildungswunsch der Kinder; Mindestausbildungsforderung;\nSparziele; Wohnungsgröße; Wohndauer; Wohnstatus; Wohngeldbezieher;\nMietkosten; Sozialwohnung; Subventionsempfang und\nEinkommenssteuerermäßigung nach § 7b; Einkommenssteuererklärung\nausgefüllt; Verkehrsmittel auf dem Weg zur Arbeit; jährliche\nKilometerleistung mit dem PKW.\n\nDemographie: Alter; Geschlecht; Familienstand; Kinderzahl; Alter der\nKinder (klassiert); Schulbildung; Berufsausbildung; Beruf; Berufliche\nPosition; Berufstätigkeit; Einkommen; Einkommen des Ehepartners;\nHaushaltsgröße; Soziale Herkunft; Charakteristika des Ehepartners.\n","spatialCoverage":{"@type":"Place","geo":[{"type":"GeoCoordinates","addressCountry":{"@type":"Country","name":"North Rhine-Westphalia"}},{"type":"GeoCoordinates","addressCountry":{"@type":"Country","name":"Schleswig-Holstein"}}]},"temporalCoverage":"03.1981 - 05.1981","contributor":{"@type":"Organization","name":"Forschungsstelle fuer empirische Sozialoekonomik, Koeln \r\n"},"license":"https://search.gesis.org/research_data/ZA1305"}</script>`

**Comment by zhangyggesis** [comment]
Thanks for your feedback !

1. The Javascript is part of our platform to distribute the data and it is enabled to increase page load speed.  
2. JavaScript generation is part of our CMS system as it increases page load times. Many systems can handle JS without a problem, the Google Dataset Search with the JSON-LD, for example.  But F-UJI has a problem with it.
3. It is fairly easy to execute JS.  For example:  https://stackoverflow.com/questions/10136319/executing-javascript-from-python has some libraries one could use to do so.
4. We suggest extending/adopting F-UJI tool to be able to execute JS and I am happy to contribute to the coding for this if needed.

**Comment by zhangyggesis** [comment]
One very easy way to get access to the JS generated content from the python environment is to use PyQt5. Using it, it can get the  script node content posted in the example above.

**Comment by zhangyggesis** [comment]
@huberrob  "We suggest extending/adopting F-UJI tool to be able to execute JS and I am happy to contribute to the coding for this if needed".  Would you please help us with our suggestion to extension?

**Comment by huberrob** [comment]
Dear @zhangyggesis this feature is not planned for the near future and as far as I know this is also not supported by any other FAIR Evaluator in the moment. So I fear I cannot help here in the short term.

You can however easily include the schema.org metadata in the HEAD section of your HTML which seems not to be JS rendered. Alternatively you can provide a typed link following the [signposting.org](https://signposting.org) conventions from @hvdsomp or [RFC 5988](https://datatracker.ietf.org/doc/html/rfc5988) leading to a metadata file.

I will also try to forward your request to the EOSC FAIR TF so we can discuss in a broader community in how far this can or shall be supported by FAIR Evaluators in the future.

**Comment by zhangyggesis** [comment]
@huberrob  Thanks for your feedback.  We are considering your suggestions.  It will be great if can inform us any feedback from EOSC FAIR regarding to this.

**Comment by zhangyggesis** [comment]
@huberrob We used typed links following the signposting.org.  we found the following.

1. when the link elements are placed in the <head> of the html landing page (see below), f-uji tool can harvester the linked metadata, 
<head>
......
   
    
    <link rel="cite-as" href="https://doi.org/10.4232/1.1305">
    
    <link rel="type" href="https://schema.org/ScholarlyArticle">
    
    <link rel="type" href="https://schema.org/AboutPage">
    
    <link rel="describedby" type="application/ld+json" href="https://multiweb.gesis.org/doip/fuji/32/10.4232/1.1305/jsonld">
    
    <link rel="license" href="https://creativecommons.org/licenses/by/4.0/">
    
    <link rel="item" href="https://api.datacite.org/application/vnd.datacite.datacite+json/10.4232/1.1305" type="application/vnd.datacite.datacite+json">
    
.....
<head>

2. when the link elements are placed in the header of the http-response of the html landing page (see below) ,fuji tool cannot harverster the metadata. 

Date: Fri, 18 Aug 2023 13:55:12 GMT
Server: Apache
link: <https://doi.org/10.4232/1.1305> ; rel="cite-as" , <https://schema.org/ScholarlyArticle> ; rel="type" , <https://schema.org/AboutPage> ; rel="type" ,  <https://multiweb.gesis.org/doip/fuji/32/10.4232/1.1305/jsonld> ; rel="describedby" ; type="application/ld+json" , <https://creativecommons.org/licenses/by/4.0/> ; rel="license" , <https://api.datacite.org/application/vnd.datacite.datacite+json/10.4232/1.1305> ; rel="item" ; type="application/vnd.datacite.datacite+json"
Content-Type: text/html;charset=utf-8
Vary: Accept-Encoding
X-Frame-Options: sameorigin
Transfer-Encoding: chunked

<html> 
......

</html>

3. Can you help us with this ? why our link element in the response header does not work?
4. For the measure FsF-A1-01M and FsF-I1-01M, embedded Json LD on the landing page gets more scores than using typed link approach.  
   4.1 In the typed link approach "access_condition" is NOT  "\/creativecommons.org\/publicdomain\/mark\/1.0\/deed.de" even though "conditionsOfAccess": "http://creativecommons.org/publicdomain/mark/1.0/deed.de", is specified in the linked Json LD. why is this?
  4.2 in the typed link approach FsF-I1-01M-1 has no score but in the embed Json LD approach , it has score.   Should we preferred one approach over another? 

I attached the linked json LD ( including the response header ( generated using from curl -i request) )
[attempt32-jsonld.txt](https://github.com/pangaea-data-publisher/fuji/files/12380318/attempt32-jsonld.txt)

Yudong

**Comment by hvdsomp** [comment]
It seems to me that this link:

https://api.datacite.org/application/vnd.datacite.datacite+json/10.4232/1.1305 ; rel="item" ; type="application/vnd.datacite.datacite+json"

should have a “describedby” relation type instead of an “item” relation type because AFAIK it links to metadata, not to content. 

I checked the landing page and saw (under Downloads) that there are 4 content resources: 3 datasets and 1 questionnaire. Links pointing to those could be provided as “item” links.

**Comment by hvdsomp** [comment]
Other than that I do not know/understand why a typed link approach should get a lesser score. Personally, I even think it should get a higher score because typed links can be provided on resources of any media type, not just html.

**Comment by huberrob** [comment]
I am not completely sure but don't the links have to be enclosed like this <https://your_link> according to rfc5988? The string has also to start with Link, not link. Maybe you can take a look at RFC 5988 and make sure you are strictly following these conventions?

A lesser score would rather be a result of differing metadata than the transport mechanism. But maybe there is a bug in F-UJI but it would be easier to discover with a working example.

**Comment by hvdsomp** [comment]
Indeed, @huberrob:

- the URLs in the links must be enclosed in “lower than” and “greater than” signs, see examples at [https://signposting.org/FAIR/#examples1](https://signposting.org/FAIR/#examples1)
- the header name is Link, not link

I had not noticed these errors. Thanks!

**Comment by zhangyggesis** [comment]
@huberrob @hvdsomp thanks your both for the information and help. I will use your suggestion to try again and see what results I can get.  Thanks !

**Comment by zhangyggesis** [comment]
I just tried as suggested and it worked for me.  F-uji tool can get the linked elements from the Link tag in the response header.  

1. I have a question regarding FsF-F2-01M-1  c and d. i.e.

c Metadata is accessible via typed links
d Metadata is accessible via signposting links

are there specific signposting links that are not typed links?

In the signposting.org page it is written as the following
---
Signposting caters to machine agents by providing this information, and more, in a standards-based way, using Typed Links as a means to clarify patterns that occur repeatedly in scholarly portals. ...

Typed links, as used in Signposting, can be provided in [HTTP Link headers](http://tools.ietf.org/html/rfc5988), [HTML link elements](https://www.w3.org/wiki/HTML/Elements/link), and [Link Sets](https://www.rfc-editor.org/rfc/rfc9264.html). This example, as well as the examples in the Patterns section of this site, uses the HTTP Link header approach: ...
---

 What is the difference between typed links and signposting links ? 

 I used the header below in the response header

 Link: <https://doi.org/10.4232/1.1305> ; rel="cite-as" , <https://schema.org/ScholarlyArticle> ; rel="type" , <https://schema.org/AboutPage> ; rel="type" ,  <https://multiweb.gesis.org/doip/fuji/34/10.4232/1.1305/jsonld> ; rel="describedby" ; type="application/ld+json" , <https://creativecommons.org/licenses/by/4.0/> ; rel="license" , <https://api.datacite.org/application/vnd.datacite.datacite+json/10.4232/1.1305> ; rel="describedby" ; type="application/vnd.datacite.datacite+json", <https://access.gesis.org/dbk/1124> ; rel="item" ; type="application/pdf"

the assessment result is:

c 	Metadata is accessible via typed links             ?   
d	Metadata is accessible via signposting links    tick

2.  When Link is in the header, it is the same as link in html head.   In the typed link approach FsF-I1-01M-1 has no score but in the embedded Json LD approach , it has score.  In other words,  embedded Json LD approach FsF-I1-01M gets score 2 of 2,  the Link approach FsF-I1-01M gets score 1 of 2.

Yudong

**Comment by hvdsomp** [comment]
First, I will assume that the URL for each link is enclosed in “lower than” and “greater than” characters. That’s not visible in your example but I’ve mentioned this requirement already above. 

Second:

- Signposting links are typed links. It’s just that, in order to achieve cross-system consistency, Signposting requires using a very small subset of all possible link relation types as listed at [https://signposting.org/FAIR/#reltypes](https://signposting.org/FAIR/#reltypes). The list of all possible IANA-registered link relation types is much larger and is listed at [https://www.iana.org/assignments/link-relations/link-relations.xhtml](https://www.iana.org/assignments/link-relations/link-relations.xhtml).
- The same link can be expressed in the HTTP Link header and in the HTML `link` element. Providing it in HTTP Link has significant advantages, including 1. the approach can be used for resources of all media types (e,g. also for PDF files) not just for HTML 2. HTTP headers, including Link, can be accessed by using HTTP HEAD, which, in contrast to HTTP GET, does not entail content transfer. Meaning with HTTP HEAD less bandwidth is used and the approach can also be used for resource with access restrictions. For more details, see [https://signposting.org/FAIR/#intro2](https://signposting.org/FAIR/#intro2).
- The embedded json-ld approach has nothing to do with Signposting. It’s a way to provide descriptive metadata by stuffing it in a `script` element inside HTML. The way Signposting provides descriptive metadata is by using a `describedby` link that points to the metadata available at a URL, just like you did in the above example. Why the Signposting approach should get a lower score, I do not know but @huberrob might know.

**Comment by huberrob** [comment]
- I made this distinction for the apples2apples hackathon so we could see if 'pure' signposting links are discovered by F-UJI
- The scoring for FsF-I1-01M just considers both options so if you have embedded RDF AND Linked RDF 1+1 = 2
- But thanks to your example I discovered another bug in F1-02D the signposting (cite-as) DOI seems to be ignored,. Once this is fixed your score should raise a bit

**Comment by zhangyggesis** [comment]
@hvdsomp yes they are encoded in < and > in the http response.  

In just found out that, by github the greater `>` and lower  `<` char in the Write mode are removed in the Preview mode.  So  in the view mode they are not there.  so I wrapped them in the code mode. now you can see that they are encoded.

`Link: <https://doi.org/10.4232/1.1305> ; rel="cite-as" , <https://schema.org/ScholarlyArticle> ; rel="type" , <https://schema.org/AboutPage> ; rel="type" ,  <https://multiweb.gesis.org/doip/fuji/34/10.4232/1.1305/jsonld> ; rel="describedby" ; type="application/ld+json" , <https://creativecommons.org/licenses/by/4.0/> ; rel="license" , <https://api.datacite.org/application/vnd.datacite.datacite+json/10.4232/1.1305> ; rel="describedby" ; type="application/vnd.datacite.datacite+json", <https://access.gesis.org/dbk/1124> ; rel="item" ; type="application/pdf"`

**Comment by zhangyggesis** [comment]
@hvdsomp @huberrob  1. I understand that Signpost links are typed links. why not for the header we used above both FsF-F2-01M-1 c and d should have a tick ?.  2.  is it the best approach for FsF-I1-01M is to use both Signpost links and embedded JsonLD on the landing page ? 3. what is the effect of  the bug in F1-02D?
