### ISSUE TITLE
F-UJI Tool Not Reading Metadata Access Rights Properly

### ISSUE THREAD

**Issue by TutasiCSUC** [pangaea-data-publisher/fuji#486]
We are currently using the F-UJI tool to assess the FAIRness of datasets within our repository hosted at https://dataverse.csuc.cat/.  

Our repository uses various metadata schemas including Dublin Core, JSON, and OpenAIRE. But, it seems that F-UJI may not be interpreting access rights information correctly from metadata.

From the issue: https://github.com/pangaea-data-publisher/fuji/issues/183 , we suppose that F-UJI is reading dublin Core schema for the metadata 'acces Rights'. In our Dublin Core metadata, the access rights information is represented as follows:

<dcterms:rights>info:eu-repo/semantics/openAccess</dcterms:rights>

Running F-UJI tests, we observed that the tool does not seem to recognize or properly interpret this access rights information. Should we change <dcterms:rights> for <dcterms:accessRights>?

**Comment by huberrob** [comment]
Can you please post an example dataset URL/DOI ?

**Comment by TutasiCSUC** [comment]
> Can you please post an example dataset URL/DOI ?

For the dataset: https://doi.org/10.34810/data514 F-UJI for 'Accessible' field, the results are: 

![image](https://github.com/pangaea-data-publisher/fuji/assets/114216855/22015b8f-f08b-4dcf-bc60-72bf39248aa7)

**Comment by TutasiCSUC** [comment]
> Can you please post an example dataset URL/DOI ?
For the dataset https://doi.org/10.34810/data899 , I get: 
![image](https://github.com/pangaea-data-publisher/fuji/assets/114216855/1d522ca8-2605-41dd-9c43-f7082fd8caa1)

**Comment by huberrob** [comment]
Thanks for this example. 
Unfortunately I cannot discover the Dublin Core property _rights_ nor _accessRights_ (both shoud be OK). 
At least these properties are  not embeded in the landing page. 

I can see this field in the export XML here: https://dataverse.csuc.cat/api/datasets/export?exporter=dcterms&persistentId=doi%3A10.34810/data514

But unfortunately this file is not linked in a way machines can see it (e.g. via typed links, signposting). 
I know Dataverse can do this, maybe you should check your Dataverse config or contact the Dataverse team and ask them about 'signposting'.

**Comment by mateuszpawlik** [comment]
Hi, yesterday I observed the same problem.

**Context:** We're developing a new repository and I wanted to quickly figure out what should we add to the metadata and how. Since it is quite difficult to find any specific information on which keys or namespaces to use (I also read through the [F-UJI paper](https://doi.org/10.1016/j.patter.2021.100370)), I started trying things out in [a test project](https://gitlab.com/ccns/neurocog/neurodataops/anc/classification/f-uji-test). We want to improve over what we have ([example website](http://bids-datasets.data-pages.anc.plus.ac.at/neurocog/soccer/)).

The [website](https://ccns.gitlab.io/neurocog/neurodataops/anc/classification/f-uji-test) generated on the [main branch](https://gitlab.com/ccns/neurocog/neurodataops/anc/classification/f-uji-test) passes the access rights F-UJI test. This version uses schema.org `"conditionsOfAccess": "http://purl.org/coar/access_right/c_16ec"`.

The [website](http://ccns.gitlab.io/-/neurocog/neurodataops/anc/classification/f-uji-test/-/jobs/7068189568/artifacts/public/index.html) generated on a [merge request](https://gitlab.com/ccns/neurocog/neurodataops/anc/classification/f-uji-test/-/merge_requests/1), with has only `"dc:accessRights": "http://purl.org/coar/access_right/c_16ec"` doesn't pass the access rights test.

The [metadata differs only by](https://gitlab.com/ccns/neurocog/neurodataops/anc/classification/f-uji-test/-/merge_requests/1/diffs) the schema.org `conditionsOfAccess` key.

schema.org correctly validates both file versions.

I don't know the F-UJI's code, but is it possible that the `accessRights` key should be somewhere in `fuji_server/helper/metadata_collector_dublincore.py`?

**Comment by huberrob** [comment]
Thanks, for the interesting examples!
This record (http://ccns.gitlab.io/-/neurocog/neurodataops/anc/classification/f-uji-test/-/jobs/7068189568/artifacts/public/index.html) specifies itself as **@type: "Dataset"** but **dc:accessRights** is not part of **schema.org/Dataset schema** and therefore ignored here

**Comment by mateuszpawlik** [comment]
Thanks. This all is rather new to me. Could you give me a hint on why exactly `dc:accessRights` is ignored? [schema.org correctly resolves it](https://validator.schema.org/#url=https%3A%2F%2Fgitlab.com%2Fccns%2Fneurocog%2Fneurodataops%2Fanc%2Fclassification%2Ff-uji-test%2F-%2Fraw%2Fd7356389e27392dceff9fc1f3b98202846e4c1bb%2Fmetadata.json)

**Comment by huberrob** [comment]
Yes the Google tool displays its presence but it as I mentioned accessRights is just not part of the schema.org/Dataset schema. The Google tools also seems to ignore non schema.org properties. You can for example change dc:accessRights to dc:abcdefg and the tool still validates it.

**Comment by mateuszpawlik** [comment]
This is what I don't understand. JSON-LD format is agnostic to the semantics of specific namespaces. I can combine multiple contexts to better describe my entity. Which mechanism is responsible for ignoring keys that are not part of schema.org type Dataset?

**Comment by huberrob** [comment]
Yes JSON-LD is the format and you are free to use additional triples or properties but you can't expect clients to understand this since you indicated a distinct schema (Dataset).  If you want clients to understand some dc terms in your JSON-LD you would have to indicate an additional type, e.g. dcat:Dataset which uses dcterms.

**Comment by mateuszpawlik** [comment]
Thanks. That helps a bit. I understand that the F-UJI tool is the client in this context, and it's up to the tool to interpret my JSON-LD file.

I also understand that, once I define the type of my entity, I should stick to its schema, for example, `dcat:Dataset` class has a different schema than `schema.org:Dataset`. I should pick one.

I don't understand how the access rights is different to `prov:atLocation` and `prov:wasGeneratedBy` which I have in my example. F-UJI recognizes the namespace (FsF-R1.2-01M-2), but it actually may not recognize these two properties, because of the same reason as in the case of access rights.

If my reasoning is correct, I wonder what's the best practice to include all these different namespaces which F-UJI requires for a higher score. I have to include a PROV-O ontology (FsF-R1.2-01M-2) but I can't use it, because the type, which I have to (or should) define (`schema.org:Dataset` or another), doesn't contain PROV-O properties.

I'm sorry if I went away from the original issue.
