### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by catgonzftw1** [pangaea-data-publisher/fuji#496]
Hi, I'm a data steward and I'd like to use this tool to try and assess how FAIR the group is currently so we can try to improve. I tried the tool and put a PID from a Coscine resource. The score returned was a 2. It gave a few errors:

WARNING | Failed to parse RDF -: https://www.ebi.ac.uk/ena/browser/view/PRJNA767532 exactly one of source, location, file or data must be given

WARNING | Landing page seems to be JavaScript generated, could not detect enough content

I've been reading the docs and I realize this tool is still being developed. Is there any trainings or discussions that are open for people interested to learn more?

**Comment by huberrob** [comment]
As this message : "WARNING | Landing page seems to be JavaScript generated, could not detect enough content" correctly reports the page is JS generated so there is not so much content F-UJI can see, this is how it looks without JS:

<img width="494" alt="image" src="https://github.com/pangaea-data-publisher/fuji/assets/356039/a8e7afb1-0c10-4f5d-9f7e-ac57044fd54a">

But I think this is not the main reason, even the JS generated page probably contains too little (machine readable) metadata or link sto metadata to be analysed. 

What would you have expected F-UJI should discover?

**Comment by catgonzftw1** [comment]
@huberrob I honestly didn't know what to expect it to return. I guess I thought because there is a PID and it is a resource with metadata in Coscine that it would have had a higher FAIR maturity level. But I'm not sure exactly how the assessment tool works.

**Comment by huberrob** [comment]
Since F-UJI is a machine, it is focusing on the machine readable metadata during the assessments. Which can be given 
For example you have used the URI 'https://www.ebi.ac.uk/ena/browser/view/PRJNA767532' which contains 'PRJNA767532' which actually is a bioproject id but the whole URI (https://www.ebi etc.) is just a URI, a unique ID which represents the landing page of the biosample ID.  

This publication: https://doi.org/10.1016/j.patter.2021.100370 describes the process of F-UJI's metadata harvesting in detail
