### ISSUE TITLE
Feedback from GeoKur project.

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [pangaea-data-publisher/fuji#73]
From Christin Henzen <christin.henzen@tu-dresden.de> @christinhenzen

Together with my colleagues from the GeoKur project (https://geokur.geo.tu-dresden.de/index.php), we reviewed the FsF Data Object Assessment Metrics document provided via your project website. From our point of view, from ESS domain and partially from a developer’s view point, lots of important aspects have been addressed, such as provenance, dataset relations and versioning. Please find a few minor comments below. What are your future plans regarding the finalization of the document and further developments? Do you give any talks in the future?

-	FsF-F2-01M: Although keeping metadata creation simple and requiring only core elements, this subset of metadata elements might be discussed. There should possibly be a way of profiling for more specific needs, e.g. either registered profiles or something similar (FsF identifier extension from "D" to "Dxx", "xx" as the registered profile). For example in ESS, we often use the spatial extent to search for data.
-	FsF-A2-01M: Do you include the case, that metadata should be available before the data is published (e.g. to the public audience)?
-	FsF-I1-01M: Would it make sense to you, to add further examples, e.g. XML metadata, or do you prefer RDF/SPRAQL due to better querying options?
-	Have you discussed aspects on metadata and data coupling, e.g. loose vs. tight coupling?

**Comment by huberrob** [comment]
Dear Cristin,

thanks for these valuable suggestions.

FsF-F2-01M: We thought about having a dedicated input parameter to specify a subset of required metadata, but this will have to wait a bit.. If you like to see this in the future, please add this as a feature request issue.

FsF-A2-01M: not this is not included since in FAIR data and metadata go as tandem. It would not be possible to assess if e.g. data will added to a dataset later.

 FsF-I1-01M: examples are always welcome! If you have some please add a list of URIs to this issue.

metadata coupling: Not sure if I understand this correctly, F-UJI can only assess data if links to data are given in the metadata and metadata is accessible. I assume this is tight coupling..

Robert
