### ISSUE TITLE
Score for PIDs assigned even when PID is not resolvable

### ISSUE THREAD

**Issue by huberrob** [pangaea-data-publisher/fuji#98]
For example this DOI is not registered
https://dx.doi.org/10.1594/PANGAEA.923903
But F-UJI considers FsF-F1-02D as 'passed' just because of the pattern matching

**Comment by ajaunsen** [comment]
In this case (non-resolvable PID) the test (FsF-F1-02F) should fail imo.

Another case, is when the input dataset is a GUID (eg. URL), but this test finds there is an PID which resolves to the input GUID – I would favour a score. This is not happening now, as you have to provide the PID for this test to pass. There should be a WARNING that the PID should be used for identification rather than the URL.

**Comment by huberrob** [comment]
I agree, I wil check the code, I think I already changed this in my local git.. Regarding the other case, I also agree. However this requires that the PID is listed as metadata or within signposting links. I think I already considered signposting. But I need to check. Maybe this is worth another issue ;)

**Comment by huberrob** [comment]
done..
